### ISSUE TITLE
在 Windows 中无法检测到 MSYS2 的终端

### ISSUE THREAD

**Issue by TimeRainStarSky** [ifrstr/isatty#2]
我在 [MSYS2](https://msys2.org) 中使用 go-cqhttp 1.0.0-rc4，会提示未检测到输入终端，但实际上存在输入终端，并且能正常输入

**Comment by ilharp** [comment]
请参阅 #3。如果你使用 Mintty 或 MSYS2，你需要参考其中提到的方法修改你的启动参数，或使用 winpty。为 CLI 应用提供控制台子系统需要由终端应用支持，这通常需要最终用户修改命令环境配置。isatty 或 go-cqhttp 层面没有办法进行处理。

如果你遇到了其他问题，请重新打开这个 issue。
